# Generated by Django 5.2.1 on 2025-05-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='source_transcription',
            field=models.TextField(blank=True, help_text='Transcription of the original media'),
        ),
    ]
