# Generated by Django 5.2.1 on 2025-05-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0002_conversation_source_transcription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='src_language',
        ),
    ]
